name: Image Upload

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Base64 encoded image'
        required: true
      filename:
        description: 'Image filename'
        required: true

jobs:
  upload_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Decode and save image
      run: |
        mkdir -p images
        echo "${{ github.event.inputs.image }}" | base64 -d > images/${{ github.event.inputs.filename }}

    - name: Commit and push image
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add images/${{ github.event.inputs.filename }}
        git commit -m "Add uploaded image"
        git push
