name: Image Upload

on:
  repository_dispatch:
    types: [upload-image]

jobs:
  upload-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create image directory if it doesn't exist
        run: mkdir -p images

      - name: Upload image
        run: |
          echo "https://github.com/Nidhi-Data-Analyst/Test1/tree/main/images/" 
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add images/${{ github.event.client_payload.filename }}
          git commit -m "Add image ${{ github.event.client_payload.filename }}"
          git push
