name: Image Upload

on:
  repository_dispatch:
    types: [image-upload]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Create image file
      run: |
        echo "${{ github.event.client_payload.content }}" | base64 -d > "images/${{ github.event.client_payload.filename }}"
